<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tinggalkan Komentar_v-icon notranslate v-icon--link mdi mdi-image-plus theme--light</name>
   <tag></tag>
   <elementGuidId>ecf835d0-5353-4875-9822-c38c1b0432fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.v-icon.notranslate.v-icon--link.mdi.mdi-image-plus.theme--light</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>37b5c2ea-ac91-4317-9b71-923c07504530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0c017e93-c1a6-4606-acd7-82923856897b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>prepend icon</value>
      <webElementGuid>2c53307c-39e0-4570-a3da-5150f7e96c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-icon notranslate v-icon--link mdi mdi-image-plus theme--light</value>
      <webElementGuid>0d5f488e-3927-4b0f-b1af-e76c78051466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/main[@class=&quot;v-main global&quot;]/div[@class=&quot;v-main__wrap&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row justify-center&quot;]/div[@class=&quot;col col-7&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;pt-3 py-1 pb-2 col col-12&quot;]/div[@class=&quot;rounded-lg mx-auto v-card v-sheet v-sheet--outlined theme--light&quot;]/div[@class=&quot;v-card__actions pa-0&quot;]/div[@class=&quot;v-list-item theme--light&quot;]/div[@class=&quot;v-list-item__content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col col-auto&quot;]/div[@class=&quot;v-input pt-0 theme--light v-text-field v-text-field--is-booted v-file-input&quot;]/div[@class=&quot;v-input__prepend-outer&quot;]/div[@class=&quot;v-input__icon v-input__icon--prepend&quot;]/button[@class=&quot;v-icon notranslate v-icon--link mdi mdi-image-plus theme--light&quot;]</value>
      <webElementGuid>13bdc726-bc72-4d38-a1e1-b4b1c4dc03ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>7b5ff110-8c6f-43cb-a6e8-cc7d305ec4ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/div[2]/div/div/div[3]/div[2]/div/div/div/button</value>
      <webElementGuid>4ccfdb5d-f205-4df7-8203-a7cd82e95da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button</value>
      <webElementGuid>40af7d92-405e-4258-bd05-425c2d741b17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>6c51eb0e-85b6-48ef-9d60-0941c595d062</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
