<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Tinggalkan Komentar</name>
   <tag></tag>
   <elementGuidId>4dce5420-2651-47b0-b1c2-745bc606d11b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.v-input__slot</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cfa87f75-a1e2-4c2a-b833-89add915b7ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-input__slot</value>
      <webElementGuid>8af3333b-f3c2-40df-b405-0ea14f94d8ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>​Tinggalkan Komentar..</value>
      <webElementGuid>d7afe724-3981-456b-95ce-36461edefc4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/main[@class=&quot;v-main global&quot;]/div[@class=&quot;v-main__wrap&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row justify-center&quot;]/div[@class=&quot;col col-7&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;pt-3 py-1 pb-2 col col-12&quot;]/div[@class=&quot;rounded-lg mx-auto v-card v-sheet v-sheet--outlined theme--light&quot;]/div[@class=&quot;v-card__actions pa-0&quot;]/div[@class=&quot;v-list-item theme--light&quot;]/div[@class=&quot;v-list-item__content&quot;]/div[2]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;v-input rounded-lg v-textarea v-textarea--auto-grow v-textarea--no-resize v-input--hide-details v-input--dense theme--light v-text-field v-text-field--is-booted v-text-field--enclosed v-text-field--outlined v-text-field--placeholder&quot;]/div[@class=&quot;v-input__control&quot;]/div[@class=&quot;v-input__slot&quot;]</value>
      <webElementGuid>8f6663c2-04fa-4395-9259-daff9b4dcdb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div/div</value>
      <webElementGuid>f8f7c7bf-3f2c-41cb-92f9-5aee8ff3e5f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='@abdul123'])[1]/following::div[35]</value>
      <webElementGuid>0aeed27d-dd7c-4933-a4d4-77657e29cea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div/div</value>
      <webElementGuid>ae672521-70f1-41d1-8afd-4653afaf56cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '​Tinggalkan Komentar..' or . = '​Tinggalkan Komentar..')]</value>
      <webElementGuid>00a857b3-da43-4e08-bcf2-b4e1410281c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
