<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Melanggar hak cipta</name>
   <tag></tag>
   <elementGuidId>ea489802-4f2d-4b44-92e9-5ad1396c11aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;app&quot;)/div[@class=&quot;v-dialog__content v-dialog__content--active&quot;]/div[@class=&quot;v-dialog v-dialog--active v-dialog--scrollable&quot;]/div[@class=&quot;v-card v-sheet theme--light&quot;]/div[@class=&quot;v-card__text pa-0&quot;]/div[@class=&quot;v-list v-sheet theme--light v-list--dense&quot;]/div[@class=&quot;v-item-group theme--light v-list-item-group primary--text&quot;]/div[@class=&quot;v-list-item v-list-item--link theme--light&quot;][count(. | //*[(text() = 'Melanggar hak cipta' or . = 'Melanggar hak cipta')]) = count(//*[(text() = 'Melanggar hak cipta' or . = 'Melanggar hak cipta')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[4]/div/div[3]/div[2]/div/div/div[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ee0b64b4-0b0f-4875-97ef-458c6a472b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d5c8dfd6-b332-4563-97ff-bf58bf2fd6df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>416bec93-fdfc-4d38-9356-42e4c9c996f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>78bf2e28-9902-4e26-9e82-ece3b76c27a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-list-item v-list-item--link theme--light</value>
      <webElementGuid>5dc35c00-3720-44eb-af98-5c6b8c297951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Melanggar hak cipta</value>
      <webElementGuid>9356ff23-a795-4260-8f1f-2fbf114fd127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-dialog__content v-dialog__content--active&quot;]/div[@class=&quot;v-dialog v-dialog--active v-dialog--scrollable&quot;]/div[@class=&quot;v-card v-sheet theme--light&quot;]/div[@class=&quot;v-card__text pa-0&quot;]/div[@class=&quot;v-list v-sheet theme--light v-list--dense&quot;]/div[@class=&quot;v-item-group theme--light v-list-item-group primary--text&quot;]/div[@class=&quot;v-list-item v-list-item--link theme--light&quot;]</value>
      <webElementGuid>190cfd44-84da-4bd1-b132-5d54ecd0df56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[4]/div/div[3]/div[2]/div/div/div[8]</value>
      <webElementGuid>1519d132-33c4-4d7b-afff-7803d1f11a79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Membahas hal melawan hukum'])[1]/following::div[1]</value>
      <webElementGuid>0a4dc39a-ce55-4316-9aa7-a1a5cb19c924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kekerasan'])[1]/following::div[4]</value>
      <webElementGuid>26684e86-f3b6-4391-bc48-b1ff323faabd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saya hanya tidak menyukainya'])[1]/preceding::div[3]</value>
      <webElementGuid>bee33c94-0bf8-49e2-878b-204518ba40c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]</value>
      <webElementGuid>b09cd3b4-b622-417f-a4ab-dab21bbf63bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Melanggar hak cipta' or . = 'Melanggar hak cipta')]</value>
      <webElementGuid>59860cac-7caa-4fa1-ac36-31d2e43dd60f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
