<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_Like Thread</name>
   <tag></tag>
   <elementGuidId>5046163d-59c7-43a3-a667-1ba578f95aaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.v-icon.notranslate.mdi.mdi-thumb-up-outline.theme--light</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/div[2]/div/div/div/div/div/div/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>192d2e5e-e8ac-4236-98e6-423f0e4bd032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>85855d06-766f-4b7c-9b33-dd20f983b039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-icon notranslate mdi mdi-thumb-up-outline theme--light</value>
      <webElementGuid>d6301592-4baf-4438-bff5-7dbb4039f3c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/main[@class=&quot;v-main global&quot;]/div[@class=&quot;v-main__wrap&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row justify-center&quot;]/div[@class=&quot;col col-7&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;pt-3 py-1 pb-2 col col-12&quot;]/div[@class=&quot;rounded-lg mx-auto v-card v-sheet v-sheet--outlined theme--light&quot;]/div[@class=&quot;v-card__actions pa-0&quot;]/div[@class=&quot;v-list-item theme--light&quot;]/div[@class=&quot;v-list-item__content&quot;]/div[@class=&quot;pa-0 col col-4&quot;]/div[@class=&quot;row justify-center&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;row align-center&quot;]/div[@class=&quot;pr-2 click-cursor col col-auto&quot;]/i[@class=&quot;v-icon notranslate mdi mdi-thumb-up-outline theme--light&quot;]</value>
      <webElementGuid>949523b4-0f56-4d30-8967-bfe608fc4209</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/div[2]/div/div/div/div/div/div/div/i</value>
      <webElementGuid>be843dfe-71c3-449d-a4de-8d52aa96a936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/i</value>
      <webElementGuid>b6478949-f461-4c02-950f-0d1dd9173ae1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
