<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Topic Food</name>
   <tag></tag>
   <elementGuidId>c0ee2fcf-046f-498b-b2e0-c0e4808dc2cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div/div/div[1]/main/div/div/div/div[1]/div/div/div/div[1]/div/div/div[4]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col.col-auto > a > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/div/div/div/div[4]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ce4b8c0c-b623-4d58-84a1-7a78036c4d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
  Architectures
</value>
      <webElementGuid>64c5dd25-5965-48af-8e7b-ab8856d04d39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div/div[1]/main/div/div/div/div[1]/div/div/div/div[1]/div/div/div[4]/a/span</value>
      <webElementGuid>4110dc63-258b-45a0-a7e4-1bad896fce40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/div/div/div/div[4]/a/span</value>
      <webElementGuid>b1d71a5d-79b5-4a05-8b73-1674a1f4c25e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[2]/following::span[1]</value>
      <webElementGuid>f328e948-fb46-42b4-80b7-e6610d72a91c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terjadi kesalahan saat memposting thread'])[1]/following::span[2]</value>
      <webElementGuid>4074273a-f1f6-46a9-a405-625d50cd2d61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='@abdul123'])[1]/preceding::span[1]</value>
      <webElementGuid>a186f934-1ab2-4365-9c63-9a496990f612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Architectures']/parent::*</value>
      <webElementGuid>709613ee-fc62-4e93-be27-eb4354b18d32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a/span</value>
      <webElementGuid>8baed0e4-2414-4084-8487-f66278e9a985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
  Architectures
' or . = '
  Architectures
')]</value>
      <webElementGuid>a4b84e95-3bef-4308-a5fd-9b6612d8c5bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
