<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Tinggalkan Komentar</name>
   <tag></tag>
   <elementGuidId>2baa0671-1fa6-429b-952f-7a09a6d41327</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-365</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;input-365&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div/div/main/div/div/div/div[1]/div/div/div/div[2]/div/div/div[2]/div/div/div/div/div/div/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>156ca6b0-6c4f-494a-acc4-a9e7d0f8882c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id=&quot;input-225&quot;</value>
      <webElementGuid>f38db2a4-2257-46a2-aff5-099d9392bdd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>fbf488cf-4f8d-4b01-bf33-dd42dc5fd3d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tinggalkan Komentar..</value>
      <webElementGuid>9bdde078-21e2-400d-9f2d-cd62fbec847e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div/div/main/div/div/div/div[1]/div/div/div/div[2]/div/div/div[2]/div/div/div/div/div/div/textarea</value>
      <webElementGuid>cae9caf5-5048-4192-9b99-fc165a131f6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='input-365']</value>
      <webElementGuid>a368c511-e1cc-4eae-84bf-cd3d996d6e2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div/div/div/textarea</value>
      <webElementGuid>6f1c9622-4cd2-492d-b63f-a1500262dcbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>6cbd2ff6-29d8-4d28-ac7b-1b2d3a9d439e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'input-365' and @placeholder = 'Tinggalkan Komentar..']</value>
      <webElementGuid>cbe9ebb8-ae1e-4b50-b156-b81b76433e5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
