<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Masukkan nama topik baru</name>
   <tag></tag>
   <elementGuidId>b681a8e2-0d22-46b0-be21-1e574df48b7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.v-messages__message</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[4]/div/div[3]/div[3]/form/div/div/div/div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>eac39b97-6b8f-4257-aed7-23d81ccd70e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-messages__message</value>
      <webElementGuid>dc9ab23f-4ee2-4a94-ae31-a43639302403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masukkan nama topik baru</value>
      <webElementGuid>0cb63d53-d1ba-49da-a0ef-e4a4202174bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div/div[4]/div/div[3]/div[3]/form/div[1]/div/div/div[2]/div[1]/div/div</value>
      <webElementGuid>d9c8e29c-0256-414c-a2ee-5235ff7cff2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[4]/div/div[3]/div[3]/form/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>31fe588f-a3a9-4002-94a0-b3106fba94f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[5]/following::div[5]</value>
      <webElementGuid>1be91754-7926-4590-8467-d0c0a58ba270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buat Topik Baru'])[1]/following::div[12]</value>
      <webElementGuid>649249ed-93ef-4afa-9226-3e44a3f3b645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[6]/preceding::div[2]</value>
      <webElementGuid>3749e8a4-467f-475e-b86d-aa9d310d2aa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[7]/preceding::div[7]</value>
      <webElementGuid>61bb79ca-1cee-4ed0-b52f-723d396f6590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Masukkan nama topik baru']/parent::*</value>
      <webElementGuid>f5eaebe9-125f-4298-bd36-fb37178607aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>20012b34-65f5-441d-8286-8a7c08576b9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Masukkan nama topik baru' or . = 'Masukkan nama topik baru')]</value>
      <webElementGuid>b9c5b3be-13cc-48f9-b393-4f34d436297d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
