<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Tambah Topic</name>
   <tag></tag>
   <elementGuidId>c7b9d493-c6a0-4078-a9b8-04b1c7b6e0e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div/div/div[2]/div/div[3]/div[1]/div/div/div/div[2]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list-item-386']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#list-item-386</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>08184f04-f7c1-41c2-9898-aead06443773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f76bc409-1136-4695-93df-4880c794c686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>list-item-386</value>
      <webElementGuid>0de15110-2384-48fd-abd0-5f0360b2c0a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-list-item theme--light</value>
      <webElementGuid>c744812e-6c0c-4710-b9bf-14020c9d596a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Tambah Topic </value>
      <webElementGuid>ff5ef9e6-bc4b-4a9b-9cd3-d17cd59270a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div/div[2]/div/div[3]/div[1]/div/div/div/div[2]</value>
      <webElementGuid>5b5578ce-5d8b-489c-a893-e0b5e381f12b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='list-item-386']</value>
      <webElementGuid>52a5ea9e-a825-43ba-b00d-2d6510cb0a10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list-363']/div[12]/div/div</value>
      <webElementGuid>f2cdd7da-dc60-4601-a7a4-62d1cc91aa6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sepak Bola'])[1]/following::div[3]</value>
      <webElementGuid>afc79db9-36ff-4edf-bb78-8dcf6ca57a23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Luar Angkasa'])[1]/following::div[9]</value>
      <webElementGuid>08f48dcb-07cb-4eee-96a8-833ed923d306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::div[6]</value>
      <webElementGuid>a6ce945b-039f-43ce-a100-1af15077d685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div</value>
      <webElementGuid>ba0b210c-3c34-4473-9c7d-39ea6ecefc61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'list-item-386' and (text() = '  Tambah Topic ' or . = '  Tambah Topic ')]</value>
      <webElementGuid>2021ce7a-4b2b-4456-a3e5-89bbb58ffafe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
