<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_deskripsi thread</name>
   <tag></tag>
   <elementGuidId>cda90eab-7196-486a-9495-0d7d4a6efbbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div/div/div/main/div/div/div/div[3]/div/div[2]/div/div/div/form/div[2]/div/div/div/div/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-191</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='input-191']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>3d8d3a61-a124-43ba-a270-e7f90755d729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-191</value>
      <webElementGuid>0a69afff-cebf-4e10-b977-a7fc50b983d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>b261ea7e-50c8-4d14-a5f5-dd3e19189607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Text (Optional)</value>
      <webElementGuid>d80bbf09-a633-4d95-b4f0-71366a211449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div/div/main/div/div/div/div[3]/div/div[2]/div/div/div/form/div[2]/div/div/div/div/textarea</value>
      <webElementGuid>963048e2-d6b1-4538-8a7a-daac45399564</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='input-191']</value>
      <webElementGuid>1db7b340-b751-490c-9747-65f11ccef584</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[3]/div/div[2]/div/form/div/div/div[2]/div/div/div/div/textarea</value>
      <webElementGuid>19b8b635-e2ed-43fd-8d3e-71415b33842f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/textarea</value>
      <webElementGuid>6e062b27-06a7-4ef2-8079-a49048c56545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'input-191' and @placeholder = 'Text (Optional)']</value>
      <webElementGuid>fc2bd93b-225b-4b94-8add-2b412800e077</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
