<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Title Thread</name>
   <tag></tag>
   <elementGuidId>8627b46d-8095-475e-8233-ec8af148a1ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div/div/div/main/div/div/div/div[3]/div/div[2]/div/div/div/form/div[1]/div/div/div/div/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-190</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='input-190']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>e9f2e769-5c60-43cf-9a7d-b74197784205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-190</value>
      <webElementGuid>f5a2c5b1-626b-4f45-a487-73607d642c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>98481859-abea-422a-8929-584a5ef83aae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input Your Title</value>
      <webElementGuid>906c9ef9-a7a2-47f9-b9bf-b052cbd858f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div/div/main/div/div/div/div[3]/div/div[2]/div/div/div/form/div[1]/div/div/div/div/textarea</value>
      <webElementGuid>e7e1ff80-b0e1-4fd6-b8c5-6043b9bf4c1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='input-190']</value>
      <webElementGuid>f86a5f8b-851a-45de-9e0c-8c9a6f8c65d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[3]/div/div[2]/div/form/div/div/div/div/div/div/div/textarea</value>
      <webElementGuid>42f2fa6d-fc00-4f38-a4f7-1295aa4cceda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>a42257e8-2f5d-4838-b387-4838d5bb13b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'input-190' and @placeholder = 'Input Your Title']</value>
      <webElementGuid>ac4d9e46-1236-4ebf-b8f3-26cfc1b5b5ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
