<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Tambah Rules (Opsional)</name>
   <tag></tag>
   <elementGuidId>c5a19524-b556-4c6a-a2ab-245dfcf33bdb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div/div/div[4]/div/div[3]/div[3]/form/div[3]/div/div/div/div/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-258</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='input-258']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1511b887-6b9d-49ec-be10-a0df9f27d491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-258</value>
      <webElementGuid>e209ed8c-bb9a-4908-86ee-31e7dd4863bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>06532f9e-c011-4560-a99a-1190385153d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tambah Rules (Opsional)</value>
      <webElementGuid>ab2a60ab-59c2-4db4-98a3-89eff0631918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div/div[4]/div/div[3]/div[3]/form/div[3]/div/div/div/div/textarea</value>
      <webElementGuid>d9cae98f-304f-4056-a164-d19baf4b01d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='input-258']</value>
      <webElementGuid>cbcc69d5-c01d-4284-b661-cc6c453bb3a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[4]/div/div[3]/div[3]/div[3]/div/div/div/div/textarea</value>
      <webElementGuid>78d7474d-9c2c-4577-ba4f-75a7766f5541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/textarea</value>
      <webElementGuid>071914d2-b849-4489-9b3b-8e8ea9288eae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'input-258' and @placeholder = 'Tambah Rules (Opsional)']</value>
      <webElementGuid>ddf94679-827b-4cb8-b932-43c0433b5bdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
