<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Deskripsi (Optional)</name>
   <tag></tag>
   <elementGuidId>dd64db71-531f-4699-b35f-53720a380cc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div/div/div[4]/div/div[3]/div[3]/form/div[2]/div/div/div/div/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-257</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='input-257']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>77e1cfb6-4705-4e20-a77b-99fedbddc2ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-257</value>
      <webElementGuid>98980cbb-4748-4eb1-acad-b3b005285fcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>5dfda046-ec12-4063-a39a-dc90633c43e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Deskripsi (Optional)</value>
      <webElementGuid>c6e45b86-004b-4761-a965-38c4f3a344a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div/div[4]/div/div[3]/div[3]/form/div[2]/div/div/div/div/textarea</value>
      <webElementGuid>294a7929-97b0-48d9-acdc-f5aae5244f7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='input-257']</value>
      <webElementGuid>e5aaa9d8-1c13-4158-938e-efd4d0dff8d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[4]/div/div[3]/div[3]/div[2]/div/div/div/div/textarea</value>
      <webElementGuid>cfcfe522-56b9-44cd-9c14-a1b19deeb3ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div/textarea</value>
      <webElementGuid>c33a9110-2a4b-4a72-941d-3e08079a3bb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'input-257' and @placeholder = 'Deskripsi (Optional)']</value>
      <webElementGuid>4cd4d00e-b431-458c-b9d4-d0eeb5cb73f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
