<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Nama Topik Baru</name>
   <tag></tag>
   <elementGuidId>8d4c9388-f9b3-46da-8955-7c0aad4cd3ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div/div/div[4]/div/div[3]/div[3]/form/div[1]/div/div/div[1]/div/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-254</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='input-254']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>14a3fe9a-0419-4528-ba54-1b0b43023b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-254</value>
      <webElementGuid>7b48870e-48d3-4bfb-9e71-e29e5bbb42f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>931aaae2-e530-475e-be73-f179c304db51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama Topik</value>
      <webElementGuid>f420283a-2b82-461e-b418-e732e2cb4427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div/div[4]/div/div[3]/div[3]/form/div[1]/div/div/div[1]/div/textarea</value>
      <webElementGuid>37a98c33-4f97-4a77-8877-019808f93232</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='input-254']</value>
      <webElementGuid>818e3725-5854-4c3e-bf6a-41eebe571348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[4]/div/div[3]/div[3]/div/div/div/div/div/textarea</value>
      <webElementGuid>a1106e63-18a1-4ab1-983a-a9b9b1367e18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/textarea</value>
      <webElementGuid>2d7d4bb9-194d-4d3c-ab1e-fcc691cf2779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'input-254' and @placeholder = 'Nama Topik']</value>
      <webElementGuid>9d1db4ee-06fa-4d05-861f-85cc95a67f07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
