<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Alert Message Null Password</name>
   <tag></tag>
   <elementGuidId>d9e3322d-4329-4534-b9da-e9d13ccd9ef3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div/div/div/form/div[3]/div/div[2]/div/div/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/div[@class=&quot;row pa-0 ma-0 align-center justify-center&quot;]/div[@class=&quot;col col-4&quot;]/div[@class=&quot;v-list-item v-list-item--three-line theme--light&quot;]/div[@class=&quot;v-list-item__content&quot;]/form[@class=&quot;v-form&quot;]/div[@class=&quot;v-input input-group--focused rounded-lg v-input--has-state v-input--dense theme--light v-text-field v-text-field--is-booted v-text-field--enclosed v-text-field--outlined v-text-field--placeholder error--text&quot;]/div[@class=&quot;v-input__control&quot;]/div[@class=&quot;v-text-field__details&quot;]/div[@class=&quot;v-messages theme--light error--text&quot;]/div[@class=&quot;v-messages__wrapper&quot;]/div[@class=&quot;v-messages__message&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.v-input.input-group--focused.rounded-lg.v-input--has-state.v-input--dense.theme--light.v-text-field.v-text-field--is-booted.v-text-field--enclosed.v-text-field--outlined.v-text-field--placeholder.error--text > div.v-input__control > div.v-text-field__details > div.v-messages.theme--light.error--text > div.v-messages__wrapper > div.v-messages__message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>00e6cd46-8c30-4d8b-a420-d1df9b92fa59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-messages__message</value>
      <webElementGuid>50852b2c-3e1c-4bb1-a9c7-6727a211d53c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masukkan password anda</value>
      <webElementGuid>4b210655-6a50-4843-9342-e8c27874a898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div/div/div[2]/div/div[2]/div/form/div[3]/div/div[2]/div/div/div</value>
      <webElementGuid>a9c110d7-dee2-4a4d-93aa-a8d53b29656b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/div/div/form/div[3]/div/div[2]/div/div/div</value>
      <webElementGuid>bebbece6-ce38-4559-b747-b942b053c0d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[3]/following::div[7]</value>
      <webElementGuid>5683620e-4d13-42a3-b595-1bbfdd61a6c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masukkan username anda'])[1]/following::div[10]</value>
      <webElementGuid>45c7675f-e534-488a-8d0c-8074a0247f80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[4]/preceding::div[1]</value>
      <webElementGuid>c6047dfb-d1c5-42d0-8fa2-951e72b54d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masukkan ulang password anda'])[1]/preceding::div[5]</value>
      <webElementGuid>36d17261-5df2-485b-a6b6-864bade24282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Masukkan password anda']/parent::*</value>
      <webElementGuid>9867f553-2361-4b31-bd6a-5755e4386a49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div</value>
      <webElementGuid>926c97e1-28b6-4277-96f7-0e56c5617a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Masukkan password anda' or . = 'Masukkan password anda')]</value>
      <webElementGuid>05fe28fd-c0de-4f0b-8dbb-9f63d382a2d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
