<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__Hide Pass Regist</name>
   <tag></tag>
   <elementGuidId>628c8211-c3a3-4845-a611-b5619deeade0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.v-icon.notranslate.v-icon--link.mdi.mdi-eye-off.theme--light</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eefc3ae8-4a80-49c1-82e5-a9c7a11db004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>83c4ac52-3c14-496f-926e-83d073a8c4db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>append icon</value>
      <webElementGuid>d8200f89-4c4a-4dc4-a22b-ef164f0311e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-icon notranslate v-icon--link mdi mdi-eye-off theme--light</value>
      <webElementGuid>ab52a7fa-1827-4a63-8021-c947aa869950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div/div/div[2]/div/div/div/form/div[3]/div/div[1]/div[2]/div/button</value>
      <webElementGuid>0c02bf7f-52c7-4d10-9f0b-7699392deb4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>06ab05e3-3754-4875-b604-c0023d7fe183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/div/div/form/div[3]/div/div/div[2]/div/button</value>
      <webElementGuid>18bc08d0-6024-4cb6-838e-aa60355730be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>2c1f4675-af80-4518-8f1a-ba3999dbb32b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>4f47947e-a816-4a96-a472-6e1d3f603f66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
