<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__UsernameRegist</name>
   <tag></tag>
   <elementGuidId>09bc9999-4868-49fd-855b-a0af4913885e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-38</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;input-38&quot;)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-38']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d23d61f3-c70f-4567-bbe5-aaba20dbb051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>7e98d849-7798-4265-8c9a-c768a6e32cd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-38</value>
      <webElementGuid>55f1a60e-96bb-4c9d-968d-50d9a454a55c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>ca9e439a-fd27-47c1-a476-3ee96553263b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eeaf376e-65fb-4803-bdd1-1b7bbd6f0770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div/div/div[2]/div/div/div/form/div[2]/div/div/div[1]/input</value>
      <webElementGuid>75408df8-3c85-4d7d-b230-2c1a0fe6e37e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-38']</value>
      <webElementGuid>9aa8026b-51c4-43cf-9c71-e26ceb7cd8c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/div/div/form/div[2]/div/div/div/input</value>
      <webElementGuid>47b8d105-5e1f-4131-b6e9-bd553841aea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>6f1596d6-6d8a-4574-a3d3-6c2cb78d2c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-38' and @placeholder = 'Username' and @type = 'text']</value>
      <webElementGuid>eec762b0-f72a-465d-bd11-8e4268993292</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
