<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ConfirmPass</name>
   <tag></tag>
   <elementGuidId>ade81379-7c85-405f-b9a8-7e89ad372767</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-45</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;input-45&quot;)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-45']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>755a6eab-57e6-4d25-86de-095aebb74b77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input-10-2</value>
      <webElementGuid>9fe0a48a-6033-477c-8a29-5cad6dc8156e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>confirm-password</value>
      <webElementGuid>8de2f7ec-6d59-4b08-be33-4e595e4eacfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-45</value>
      <webElementGuid>94713228-17d0-49fc-a4ea-79c38b9e21e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Confirm Password</value>
      <webElementGuid>b2a571dc-1fe3-45ba-9973-376f745a6fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>025c2e0a-c415-41ec-8281-71750f7a7016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div/div/div[2]/div/div/div/form/div[4]/div/div/div[1]/input</value>
      <webElementGuid>45a0eeb8-2dd6-4373-9daf-53b493efc0a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-45']</value>
      <webElementGuid>46604c1f-78e4-4cf4-8917-603c4595500f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/div/div/form/div[4]/div/div/div/input</value>
      <webElementGuid>1313da49-920d-4fdb-9d2e-e651b5b2cca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>6acf846e-bc43-4e0b-a482-141b6def4445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'input-10-2' and @id = 'input-45' and @placeholder = 'Confirm Password' and @type = 'password']</value>
      <webElementGuid>27cd8562-7a0e-451e-970b-e46d94863aed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
