<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ignore Thread</name>
   <tag></tag>
   <elementGuidId>7a943851-1fe0-4f2f-975b-11caca9c95d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list-item-1181']/div[2]/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div/div/div[2]/div/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#list-item-1181 > div.v-list-item__content > div.v-list-item__title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ec3d5cfa-62ae-4805-bb61-7b66cc6b8835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-list-item__title</value>
      <webElementGuid>8549ecc7-4fee-4751-abc3-df0b895d0e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ignore</value>
      <webElementGuid>2159db29-ea41-4883-b436-37ad054648fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div/div[2]/div/div[2]/div[2]</value>
      <webElementGuid>b16566f9-c6ce-4a39-92eb-2eeaf37f6306</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list-item-1181']/div[2]/div</value>
      <webElementGuid>bf8e4c06-b3c6-4f42-9da8-c4daaa4c1ba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forward'])[1]/following::div[4]</value>
      <webElementGuid>bdd3d0d0-eac4-46f1-8d9c-1bdb703c6ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::div[1]</value>
      <webElementGuid>0a374c82-0693-49a8-94d3-d0571a4ede6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::div[1]</value>
      <webElementGuid>6475d5fc-1d5e-4204-9e72-b3ad6530cd47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ignore']/parent::*</value>
      <webElementGuid>0ab3c721-462a-4b99-88a6-56474e758be9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div</value>
      <webElementGuid>e8c0f110-3053-4a33-be01-174f99ebe165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Ignore' or . = 'Ignore')]</value>
      <webElementGuid>29a6f792-9ac6-4baa-8fd2-038ac1c4900e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
