<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Titik Tiga Approve</name>
   <tag></tag>
   <elementGuidId>33536042-9525-4d0f-bbbd-87a1bda62c29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div/section/div/div/div/div[9]/div[2]/div/div/section/div/div/table/tbody/tr/td/div/div[3]/div/div/div[3]/p</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div/div/div/main/div/section/div/div/div/div[9]/div[2]/div/div/section/div/div[1]/table/tbody/tr[1]/td/div/div[3]/div/div/div[3]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>03e05ece-0682-475b-a5ff-93bec0a8f5d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1f76651c-6cb3-47c1-8cc6-fdcf7913a8b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1868db88-a2db-48a1-8763-8c4e455b502b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8544a011-4041-4499-900d-bfda74c3e00b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ma-0</value>
      <webElementGuid>3807ce74-f7a5-400b-bb9b-da6d416ef42e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    ···
                                  </value>
      <webElementGuid>67c76734-e59a-4d9c-98b4-6f89c9f19942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div/div/main/div/section/div/div/div/div[9]/div[2]/div/div/section/div/div[1]/table/tbody/tr[1]/td/div/div[3]/div/div/div[3]/p</value>
      <webElementGuid>c3a167ff-7b59-4ce8-a3ed-70b9d8553dec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/section/div/div/div/div[9]/div[2]/div/div/section/div/div/table/tbody/tr/td/div/div[3]/div/div/div[3]/p</value>
      <webElementGuid>c561bc43-139c-42a1-80d5-b1ecf11a82b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='@AdminNomiz...'])[1]/following::p[4]</value>
      <webElementGuid>e496fb44-966b-4d04-b3a3-3d9649c941bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forward'])[1]/preceding::p[1]</value>
      <webElementGuid>fbab1799-614d-4f91-9aa1-cc93541ab638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='···']/parent::*</value>
      <webElementGuid>3a9fed91-6b9e-4c14-b801-82c7379ffb1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/p</value>
      <webElementGuid>e1e96831-4547-49cd-b2d5-169e4860912f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '
                                    ···
                                  ' or . = '
                                    ···
                                  ')]</value>
      <webElementGuid>ff638c36-fcfa-44db-a7f9-587bd8f17ac1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
