<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Titik Tiga Ignore</name>
   <tag></tag>
   <elementGuidId>b49e93ba-b0d8-47d2-b6cf-5e0c41b2e1af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div/section/div/div/div/div[9]/div[2]/div/div/section/div/div/table/tbody/tr/td/div/div[3]/div/div/div[3]/p</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div/div/div/main/div/section/div/div/div/div[9]/div[2]/div/div/section/div/div[1]/table/tbody/tr[2]/td/div/div[3]/div/div/div[3]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>007ef926-e7ea-4897-8d05-f0e45b20e34f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5e314869-d51d-48d4-aa5a-e9b1b59e205b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c0e67b7d-8ead-43eb-bf1f-f7f1a28e4693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5fc39cbb-06f5-4002-be32-76d1a69346cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ma-0</value>
      <webElementGuid>ef8645fc-bfb5-46b9-bfc4-dc38c71c8b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    ···
                                  </value>
      <webElementGuid>d34b03cd-9caf-4938-a43c-3b9b3cd86122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div/div/main/div/section/div/div/div/div[9]/div[2]/div/div/section/div/div[1]/table/tbody/tr[2]/td/div/div[3]/div/div/div[3]/p</value>
      <webElementGuid>3eb62c6a-b51e-48a8-98b5-04b6ae22dbdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/section/div/div/div/div[9]/div[2]/div/div/section/div/div/table/tbody/tr/td/div/div[3]/div/div/div[3]/p</value>
      <webElementGuid>06724479-0ac2-4d4d-9066-4bdd8fa9f6fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='@AdminNomiz...'])[1]/following::p[4]</value>
      <webElementGuid>781a8258-058b-4cd5-813f-86bde386f1e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forward'])[1]/preceding::p[1]</value>
      <webElementGuid>ca4b8dd2-a761-47a6-ab45-a9db86669072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='···']/parent::*</value>
      <webElementGuid>6db62012-2747-496b-b872-178ac6201896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/p</value>
      <webElementGuid>c446ef9c-3fd3-4459-bfa7-b1097e6690d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '
                                    ···
                                  ' or . = '
                                    ···
                                  ')]</value>
      <webElementGuid>d6137c59-b250-4792-a474-6dca88855670</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
