<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Validasi Comment Laporan Pengguna</name>
   <tag></tag>
   <elementGuidId>33502302-cf96-4fc8-be79-805cbdc499fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div/div/main/div/section/div/div/div/div[9]/div[2]/div/div[2]/section/div/div[1]/table/tbody/tr/td</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>b3115116-4617-46c4-a46a-e39d84fbab27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div/div/main/div/section/div/div/div/div[9]/div[2]/div/div[2]/section/div/div[1]/table/tbody/tr/td</value>
      <webElementGuid>d8325882-8e51-48ae-a686-92fe61388077</webElementGuid>
   </webElementProperties>
</WebElementEntity>
