<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Alert_Username atau password yang anda masukkan salah</name>
   <tag></tag>
   <elementGuidId>92ad4d76-1d04-4a3f-afe8-5ffa48bea546</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.v-snack__content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fdfa4d80-0054-49a0-ab23-06f2f86a7bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>a4ed2308-78e4-4799-a6d3-837b88b4f78a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>d7db15d8-9e35-4992-8940-9c3e022641c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-snack__content</value>
      <webElementGuid>62aa1d49-4f0b-4986-adcb-c807b4588a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    Username atau password yang anda masukkan salah
    </value>
      <webElementGuid>1ac7aa4a-84ea-40ac-90d2-75ffeab419fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/div[@class=&quot;v-snack v-snack--active v-snack--bottom v-snack--has-background&quot;]/div[@class=&quot;v-snack__wrapper v-sheet theme--dark&quot;]/div[@class=&quot;v-snack__content&quot;]</value>
      <webElementGuid>7c287ff0-b057-4fb2-adeb-1de078859008</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div</value>
      <webElementGuid>31993622-11ce-40ad-a8ca-709bc9cc6cd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::div[1]</value>
      <webElementGuid>2b6b581f-9c3b-4e83-b289-ee24a7e38d96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[1]/preceding::div[8]</value>
      <webElementGuid>2df0fb6e-3ef7-43c1-b9e5-638d6957bf5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Username atau password yang anda masukkan salah']/parent::*</value>
      <webElementGuid>095b272f-63f4-4d95-8a97-1771af17c8c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div</value>
      <webElementGuid>1b4658d9-2211-42a3-b735-d8308c843aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
    Username atau password yang anda masukkan salah
    ' or . = '
    Username atau password yang anda masukkan salah
    ')]</value>
      <webElementGuid>29aa73d2-89c2-40d3-a198-8062f5786018</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
