<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_User Budi-Man</name>
   <tag></tag>
   <elementGuidId>5edf89b8-c40c-4b6b-99cd-7d3bd3d2c4fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/a/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div/div/div/main/div/div/div/div[2]/div/div[2]/div/div/div/div[1]/div[4]/div/div/div[1]/a/div/div[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ab43f971-f4d1-4efc-bc8e-8672ac16d2d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row</value>
      <webElementGuid>dd5a1ca7-89e7-45a8-9e90-ced4f05819d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2.  
  @UniqueUser9
</value>
      <webElementGuid>63fcdf1a-3364-4f32-9930-5a863506cc8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div/div/main/div/div/div/div[2]/div/div[2]/div/div/div/div[1]/div[4]/div/div/div[1]/a/div/div[3]/span</value>
      <webElementGuid>a3c6509b-3145-41c7-94ce-a42175e65c70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/a/div</value>
      <webElementGuid>a230280f-9bc6-477b-b02b-7005e4f7a5a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Follow'])[6]/following::div[4]</value>
      <webElementGuid>f0de71a4-7bab-43ef-8032-9e50b0bca987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='@UniqueUser7'])[2]/following::div[5]</value>
      <webElementGuid>414eb150-4c7a-432b-9f15-30c6d1098f43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Follow'])[7]/preceding::div[9]</value>
      <webElementGuid>539c41d3-b358-4ddc-963e-7b7fe680a15e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div/div/a/div</value>
      <webElementGuid>56c77207-55a0-4d4e-bf00-767f585bc555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '2.  
  @UniqueUser9
' or . = '2.  
  @UniqueUser9
')]</value>
      <webElementGuid>ecf185ff-c48b-4e1c-b069-04354ac5036d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
