<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search Topic</name>
   <tag></tag>
   <elementGuidId>204c43c0-556a-44e1-8e93-1f5bf133968d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div/div/div/main/div/section/div/div/div/div/div[1]/div[2]/div/div/div[1]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-195</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-195']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea7f001d-0bda-450a-b149-f2272d5f130e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-195</value>
      <webElementGuid>ef495b04-0a5c-40f4-b86b-6612dee767d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>846b7887-c6ee-44e6-a0d6-ec3cc3b420d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div/div/main/div/section/div/div/div/div/div[1]/div[2]/div/div/div[1]/input</value>
      <webElementGuid>91b7b6ac-8bc5-4a7d-83ac-71e9e1409182</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-195']</value>
      <webElementGuid>5dc613e8-8ff8-45a1-926a-ccf9aa3e753c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/section/div/div/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>d9512d66-3be3-4b12-b36f-fe737aeaa8f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>fc3b7153-770c-4b8d-af4c-a9ef01a942ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-195' and @type = 'text']</value>
      <webElementGuid>609c338e-d209-4fed-bd3d-2c8e6e530f84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
