<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search bar Topics</name>
   <tag></tag>
   <elementGuidId>48b0e740-693b-48fe-8efc-2eec6b81f98a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-250</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-250']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2dd0945d-5e63-4605-a076-7c25e9bfaf0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-250</value>
      <webElementGuid>3f6a46ba-dff8-43b6-942d-1d1178be278c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5969d089-3326-4a88-9edf-7048e52eb40f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div/div[1]/main/div/div/div/div[2]/div[2]/div/div/div/div[1]/input</value>
      <webElementGuid>be455c9e-77fe-459b-94d8-790809e987ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-250']</value>
      <webElementGuid>5c1385fc-3349-4478-8d48-e2b7ed37baf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>029c7eba-2892-4b0c-8351-09109355d114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>59445cb7-5675-48c5-b231-1ae1321d1176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-250' and @type = 'text']</value>
      <webElementGuid>80c2a632-6a64-4d3c-b033-6f7cec8875a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
