<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Div_Sort by Status</name>
   <tag></tag>
   <elementGuidId>daad5366-fc6d-4100-87f8-044e3f56548c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div/div/div[2]/div/div/div[2]/div/table/thead/tr/th[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div/div/main/div/section/div/div/div/div/div[2]/div[1]/table/thead/tr/th[2][count(. | //*[(text() = 'Status' or . = 'Status')]) = count(//*[(text() = 'Status' or . = 'Status')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>th.text-center.sortable.active.asc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>fce93c4f-dcf3-4c40-bcd6-487a21324218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>columnheader</value>
      <webElementGuid>75149b34-c2e9-4059-a989-b28f7a858ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>col</value>
      <webElementGuid>731e093f-040c-492d-a4a9-ca89a6a36aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Status: Sorted ascending. Activate to sort descending.</value>
      <webElementGuid>8d3b520a-dc19-4f19-a6fc-ca84df0094b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-sort</name>
      <type>Main</type>
      <value>ascending</value>
      <webElementGuid>91c97cec-a7e0-4c4c-af15-110bbe728689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center sortable active asc</value>
      <webElementGuid>232aa03a-f6e4-4e09-bdb8-98cbf5e84de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Status</value>
      <webElementGuid>78182b51-9afd-43ba-93ac-ea414ecb2ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div/div/main/div/section/div/div/div/div/div[2]/div[1]/table/thead/tr/th[2]</value>
      <webElementGuid>b3034766-fcfe-4098-b4ad-e651ba018309</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[2]/div/div/div[2]/div/table/thead/tr/th[2]</value>
      <webElementGuid>6cdfba9a-911a-4373-ac87-486758536e62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User'])[2]/following::th[1]</value>
      <webElementGuid>c0437274-5acf-4a7c-b19d-eae2b5f26caa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[3]/following::th[2]</value>
      <webElementGuid>86909f46-8d32-4f27-8082-a69601cbbf18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Post Created'])[1]/preceding::th[1]</value>
      <webElementGuid>6fbb45b1-ec3e-4c4a-af14-63fc6ac5c687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[2]</value>
      <webElementGuid>aca57c66-ba34-4cfe-8a5e-6b94cc29ab68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Status' or . = 'Status')]</value>
      <webElementGuid>28686b4d-cb63-4d2b-a2e4-e62f5b4e607d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
