<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search bar Users Page</name>
   <tag></tag>
   <elementGuidId>e0b4d781-205a-4e91-b07e-beeaeb8d368e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-195']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div/div/main/div/section/div/div/div/div/div[1]/div[2]/div/div/div[1]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-195</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef19eddb-6a33-4cd4-b1b0-d9ded0f74e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-195</value>
      <webElementGuid>080a9ac8-e83f-4739-842f-13765473f289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5f200ca4-7a08-4b2b-ae17-627f87a4012d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div/div/main/div/section/div/div/div/div/div[1]/div[2]/div/div/div[1]/input</value>
      <webElementGuid>4e46e323-9b53-44d2-942b-72bb4b7b3488</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-195']</value>
      <webElementGuid>4c757a2c-827f-428e-9ac5-b5ffa289bcbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[2]/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>d62eba63-e55d-41af-b1d7-79e9ac06cb23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f8ef0d88-4b27-44c1-a1a5-11651c00e606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-195' and @type = 'text']</value>
      <webElementGuid>918fa204-687a-4e89-81d7-9139ce3bfd67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
