<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Validasi_Berhasil meminta menjadi moderator</name>
   <tag></tag>
   <elementGuidId>ea225ad4-5345-4b25-9ca4-a1bce010d171</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.v-snack__content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0f84cc84-dd24-4d59-8b76-37f4645de16e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>f011526f-8284-4ed5-8c72-8238b36acc72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>b59273b2-bf80-42cc-870d-9133e6bedc3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-snack__content</value>
      <webElementGuid>f16525bd-c95a-49df-86d4-2ad81f0ac6ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    Berhasil meminta menjadi moderator
    </value>
      <webElementGuid>9bc4b737-ecb7-430f-acca-dbe2e7606db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div/div/main/div/div/div[1]/div/div[1]</value>
      <webElementGuid>4a2b0270-69f5-4103-8b35-3b37cfa8df12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div</value>
      <webElementGuid>0e88f994-fd32-4f6d-896f-0afe125998eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User'])[1]/following::div[6]</value>
      <webElementGuid>908953ca-5044-44d7-a606-955d8918f332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elfnov1234'])[1]/following::div[8]</value>
      <webElementGuid>351d04bc-13c8-4fde-88de-5fde72371fbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::div[1]</value>
      <webElementGuid>41c69923-3059-48c2-b3f1-d7723fd28735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terjadi kesalahan saat meminta menjadi moderator'])[1]/preceding::div[2]</value>
      <webElementGuid>63567349-d1eb-4d8a-bcd1-b5f27564b6d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Berhasil meminta menjadi moderator']/parent::*</value>
      <webElementGuid>a2afff95-f6de-45cc-a5e5-14ce3c73026f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div/div/div</value>
      <webElementGuid>5eafa178-e971-436d-8b0f-e193d3511ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
    Berhasil meminta menjadi moderator
    ' or . = '
    Berhasil meminta menjadi moderator
    ')]</value>
      <webElementGuid>8533a44a-0894-407e-abab-6cdc6ac584c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
