<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Sorry, your password was incorrect. Pleas_47a749</name>
   <tag></tag>
   <elementGuidId>d1f7dd33-cdf7-456c-ad19-7f8f1527b22d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#slfErrorAlert</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='slfErrorAlert']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>75bbbfa5-189b-4476-8ff6-9a091afd882c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-atomic</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>80a7d74c-0b83-4a26-bec9-e44a9bcbb0b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>login-error-message</value>
      <webElementGuid>318e2711-0ccc-4d27-ac2c-c3556c2f0258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>slfErrorAlert</value>
      <webElementGuid>5f3ab5ed-e3b3-42c3-a770-e4173e20d9d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>77e2d943-39b6-4156-8abe-706ed57bff7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sorry, your password was incorrect. Please double-check your password.</value>
      <webElementGuid>80f4fe26-b033-40cb-a421-1c61a36af651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slfErrorAlert&quot;)</value>
      <webElementGuid>d16ee0f8-f238-46a8-8cdd-b7f10622ccf1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='slfErrorAlert']</value>
      <webElementGuid>66f339d7-d106-4ebc-8836-45d42217faae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginForm']/div[2]/p</value>
      <webElementGuid>c8dab451-7d88-4cc6-a5f5-f3a020245712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in with Facebook'])[1]/following::p[1]</value>
      <webElementGuid>e7383abc-74d6-495c-8a24-de3f7c6eac00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='or'])[1]/following::p[1]</value>
      <webElementGuid>32e4118b-58d6-4df0-8979-d3d384ec85fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot password?'])[1]/preceding::p[1]</value>
      <webElementGuid>ebb53f58-5910-45f4-96a4-195a9d556421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up'])[1]/preceding::p[1]</value>
      <webElementGuid>258c4710-0467-4c09-aa2a-866f1e37f1e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sorry, your password was incorrect. Please double-check your password.']/parent::*</value>
      <webElementGuid>231fd54e-f139-4df8-be2e-9e68be5bb0f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>371b8886-d6dd-429d-a627-0fddd46462d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'slfErrorAlert' and (text() = 'Sorry, your password was incorrect. Please double-check your password.' or . = 'Sorry, your password was incorrect. Please double-check your password.')]</value>
      <webElementGuid>e502f5d9-c137-436d-ba1a-400ae0d2111b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
