<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Titik Tiga Report Reply</name>
   <tag></tag>
   <elementGuidId>a11e3a5b-12d9-4d92-981d-5ff2c3af9ec9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div/div/div[3]/div/div/div/div/div[2]/div/div/div[4]/div/div/div[2]/div[3]/div[4]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col.col-10 > div.row > div.col > p.ma-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>6da9ac46-9cbe-4e43-a70d-b9eb2ceec934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>72dbb259-c15d-44e0-a629-a7c9de131597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>22d36e97-88bc-49f5-855e-6d464a06e593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9d5edace-249f-421a-b7c4-f3ccd3fa2338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ma-0</value>
      <webElementGuid>d69264c3-399e-41f5-8bc2-8fa04f1dad1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
              ···
            </value>
      <webElementGuid>4ea53a42-00a8-41e9-bc0a-8a396191d136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div/div/main/div/div/div[3]/div[1]/div/div/div/div[2]/div/div/div[4]/div[1]/div/div[2]/div[3]/div[4]/p</value>
      <webElementGuid>48649160-44e7-465c-be8c-0cd2f1784691</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[3]/div/div/div/div/div[2]/div/div/div[4]/div/div/div[2]/div[3]/div[4]/p</value>
      <webElementGuid>1fa19b03-9e00-4ed8-be72-32891c70e90a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Komentar'])[1]/following::p[2]</value>
      <webElementGuid>375a0ece-ae07-4a97-8b56-d09c6819f150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='donat yang bolong tengahnya'])[1]/following::p[2]</value>
      <webElementGuid>fb5893b0-6428-4bfe-a61e-ac6526bdf5f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='@Elfnov1234'])[2]/preceding::p[1]</value>
      <webElementGuid>bd74fdf0-2be1-422a-a4a1-4c63de68668a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='donat yang bolong tengahnya'])[2]/preceding::p[1]</value>
      <webElementGuid>b2a4bcff-e75a-432d-9f71-033f0d93e040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/p</value>
      <webElementGuid>f0823959-db8e-49de-81b5-9c41e37c58cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '
              ···
            ' or . = '
              ···
            ')]</value>
      <webElementGuid>5eb44184-ab02-41ad-9433-28de13aaecd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
