<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ubah Deskripsi</name>
   <tag></tag>
   <elementGuidId>717d3d97-c414-4c05-a45b-3fa953ab84b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.text-capitalize.v-btn.v-btn--outlined.v-btn--text.theme--light.v-size--default</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b5e0e439-42e7-4278-bb7e-c12766aeb35c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f4e3be3a-1d3f-4d2e-a53c-8fdab3121191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-capitalize v-btn v-btn--outlined v-btn--text theme--light v-size--default</value>
      <webElementGuid>75ad69ee-f61f-45f5-8354-9ff62c19a6aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          Ubah
        </value>
      <webElementGuid>f72334ae-5a4c-4a85-80c9-435e6a981c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/main[@class=&quot;v-main global&quot;]/div[@class=&quot;v-main__wrap&quot;]/div[@class=&quot;container py-0&quot;]/div[@class=&quot;rounded-lg pa-4 v-card v-sheet v-sheet--outlined theme--light&quot;]/div[@class=&quot;row align-center&quot;]/div[@class=&quot;col col-auto&quot;]/button[@class=&quot;text-capitalize v-btn v-btn--outlined v-btn--text theme--light v-size--default&quot;]</value>
      <webElementGuid>f3f9676a-f581-4c80-b233-0deb6dbb7d3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[9]</value>
      <webElementGuid>541c7f32-6b3c-484d-a834-6c78fb45460b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[7]/div[2]/div[2]/button</value>
      <webElementGuid>50c515e6-82fb-489c-ae14-6fb8baa042cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deskripsi'])[1]/following::button[1]</value>
      <webElementGuid>3e0de8ea-b4b5-413e-b5c2-17a1cb7f30bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keluar Sebagai Moderator'])[1]/following::button[1]</value>
      <webElementGuid>b35577c8-8ac1-44e7-abf9-518bdfa92d42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua hal tentang makanan'])[1]/preceding::button[1]</value>
      <webElementGuid>7319543e-8d1f-48f8-b7de-2b086176d8a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>b873a30f-87e3-484b-80fe-7ef9524ad387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
          Ubah
        ' or . = '
          Ubah
        ')]</value>
      <webElementGuid>6c36d27e-f744-4bb9-91ca-81f72952809c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
