<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Laporan Pengguna</name>
   <tag></tag>
   <elementGuidId>132ee93c-ab8c-49b3-b9ba-cfbb7a2865d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.text-overline</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div/div/div[7]/div[5]/div/div/div/div/div[2]/div[2]/a/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e6734bd6-eaca-4f0e-99ce-cb5bbb225550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-overline</value>
      <webElementGuid>3edb2c8d-0216-49e8-8e7e-15c04ed31ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Laporan Pengguna</value>
      <webElementGuid>07295111-a576-4348-a66b-31936078226e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/main[@class=&quot;v-main global&quot;]/div[@class=&quot;v-main__wrap&quot;]/div[@class=&quot;container py-0&quot;]/div[@class=&quot;rounded-lg pa-4 v-card v-sheet v-sheet--outlined theme--light&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;rounded-lg pa-4 v-card v-sheet v-sheet--outlined theme--light&quot;]/div[@class=&quot;v-list-item v-list-item--three-line theme--light&quot;]/div[@class=&quot;v-list-item__content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col col-12&quot;]/a[1]/div[@class=&quot;row align-center&quot;]/div[@class=&quot;pl-0 col col-auto&quot;]/div[@class=&quot;text-overline&quot;]</value>
      <webElementGuid>1ced71e8-a286-4214-9ba7-4f633a0ba48a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[7]/div[5]/div/div/div/div/div[2]/div[2]/a/div/div[2]/div</value>
      <webElementGuid>343b2baf-8b8c-45db-98a6-0e5e8beb54db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='@AdminNomiz...'])[1]/following::div[14]</value>
      <webElementGuid>a04903d0-abab-45d7-84f3-7897d04f14c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laporan Pengguna Terbaru'])[1]/following::div[25]</value>
      <webElementGuid>be6fea6a-b2b6-439f-85bf-9ac4f42342e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::div[1]</value>
      <webElementGuid>65167cf2-cefb-4e4d-bd50-32291af66e4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::div[1]</value>
      <webElementGuid>c1ada713-d44d-4f8f-af5e-dc29c0029c5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Laporan Pengguna']/parent::*</value>
      <webElementGuid>937051a4-c515-4b82-a502-9069bbd322dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div[2]/div</value>
      <webElementGuid>b654bc07-edab-4c1f-82dc-6b47768c375c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Laporan Pengguna' or . = 'Laporan Pengguna')]</value>
      <webElementGuid>986717c7-9bcb-4056-a396-ef18dec0755d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
