<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Categories Tensi Darah Elektrik</name>
   <tag></tag>
   <elementGuidId>84a93271-3abf-4674-84fa-79d2a8629ceb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#list-item-1234-5 > div.v-list-item__content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list-item-1234-5']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>68f6deb5-2900-4b53-98a6-3c0de0ef0246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-list-item__content</value>
      <webElementGuid>f390b362-36b5-4f3b-b0e3-33014a39c04e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tensi Darah Elektrik</value>
      <webElementGuid>1a0450ac-88bf-4fbf-aeae-2d7099551848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list-item-1234-5&quot;)/div[@class=&quot;v-list-item__content&quot;]</value>
      <webElementGuid>7e128060-4693-419f-b352-f4fe22c00277</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list-item-1234-5']/div</value>
      <webElementGuid>4cfd642d-6d1d-4e90-9bbf-13c709ca22bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kesehatan'])[9]/following::div[2]</value>
      <webElementGuid>89e9b545-d9b3-4f35-b864-a074369163c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='alat'])[2]/following::div[5]</value>
      <webElementGuid>ce3b51ae-f303-42e7-a627-14e237b41f7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kesehatan'])[10]/preceding::div[2]</value>
      <webElementGuid>52767158-0788-4fc4-8967-7a46680f9692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[6]/div</value>
      <webElementGuid>255a0f58-8cb3-42f9-8e4a-df418bdaa139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Tensi Darah Elektrik' or . = 'Tensi Darah Elektrik')]</value>
      <webElementGuid>49e929ef-ab63-41ab-b07e-45f7747196ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
