<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ranking Search Bar</name>
   <tag></tag>
   <elementGuidId>e2882c3b-18fc-49c1-8326-e4fd85744f58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div/div/div/main/div/section/section/div/div/div[3]/div/div/div/div[1]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-194</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-194']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ad6cfbcd-3c3b-45d7-a6d9-4315915f2f13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-194</value>
      <webElementGuid>461fa492-ae26-46b1-9a71-e66a113f9487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c619c7dd-b01c-4914-b586-b9833bff3a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div/div/main/div/section/section/div/div/div[3]/div/div/div/div[1]/input</value>
      <webElementGuid>71916480-e6d6-4544-b127-a1772a51046e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-194']</value>
      <webElementGuid>1f5bcdcc-675a-4bde-aac8-e024268ded4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/section/section/div/div/div[3]/div/div/div/div/input</value>
      <webElementGuid>ab265f74-f908-4e46-b787-f1826807ed26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3b72a44b-112c-4670-a84a-2c337fdadc1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-194' and @type = 'text']</value>
      <webElementGuid>41d6ac16-dac9-4ed3-a48a-c3de89bae3eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
