<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Ranking Page</name>
   <tag></tag>
   <elementGuidId>627b57ea-c21f-458c-b029-4465d49d3bef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/header/div/section/a[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>292841e0-1316-4b9d-9f3a-03dc0616c84a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ranking</value>
      <webElementGuid>2d0893b2-eb0d-49ea-917d-985e78e0a793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-btn v-btn--router v-btn--text theme--light v-size--default</value>
      <webElementGuid>43ff0174-4465-430d-adc8-e087f11d1d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      Ranking
    </value>
      <webElementGuid>84fac2dd-9835-4680-acdc-4b82738432ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/header[@class=&quot;v-sheet theme--light v-toolbar v-app-bar v-app-bar--fixed&quot;]/div[@class=&quot;v-toolbar__content&quot;]/section[1]/a[@class=&quot;v-btn v-btn--router v-btn--text theme--light v-size--default&quot;]</value>
      <webElementGuid>059599b9-ad2b-4f0c-91c2-9a96ce8ca110</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/header/div/section/a[3]</value>
      <webElementGuid>75785d27-780f-4164-82c9-209b537c9259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stations'])[1]/following::a[3]</value>
      <webElementGuid>91cff63e-0972-4efb-85ec-e6d8fada57fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ranking'])[1]/following::a[4]</value>
      <webElementGuid>3ba61def-5475-4fa7-8db2-a3036ebb0741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elf123456'])[1]/preceding::a[4]</value>
      <webElementGuid>d8a9dbc7-64f8-4c97-a14b-f132500d70e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User'])[1]/preceding::a[4]</value>
      <webElementGuid>a7707bd5-948f-4c2c-9cfe-7e33767ce5dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/ranking')])[2]</value>
      <webElementGuid>db5430ca-3cd5-476e-aae1-2a61aea1665f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div/section/a[3]</value>
      <webElementGuid>1893c5e6-ebb6-41aa-bc83-2807389eb551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ranking' and (text() = '
      Ranking
    ' or . = '
      Ranking
    ')]</value>
      <webElementGuid>fa4648d5-8135-49ef-9a3f-c099fdf21534</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
