<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Username pakBudRT03</name>
   <tag></tag>
   <elementGuidId>7085a89c-a762-4ec7-bb82-2bd3526190ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.text-overline > span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div/div/div[1]/main/div/div/div/div[2]/div/div[1]/div/div/div/div[2]/div/div[2]/div/span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div/div/div/div[2]/div/div/div/div/div/div[2]/div/div[2]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3257c69a-aa57-4030-bea9-46523673cce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
  @pakBudRT03
</value>
      <webElementGuid>81affff5-e145-468b-ba98-8fdec2c9d394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div/div[1]/main/div/div/div/div[2]/div/div[1]/div/div/div/div[2]/div/div[2]/div/span</value>
      <webElementGuid>9e10294d-6b0d-467a-8c37-f9d9825826ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/div/div/div/div/div/div[2]/div/div[2]/div/span</value>
      <webElementGuid>da4d9a30-fb49-43b5-b83b-b8dceb6d91a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Follow'])[1]/preceding::span[1]</value>
      <webElementGuid>03e9b0d9-f28d-4e36-98c4-769e5fe849ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='@pakBudRT03']/parent::*</value>
      <webElementGuid>9801edd4-5263-476b-9401-34d717ccc3ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span</value>
      <webElementGuid>466d775e-b503-4085-8c7d-79363524d85b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
  @pakBudRT03
' or . = '
  @pakBudRT03
')]</value>
      <webElementGuid>5d8b64cc-dfce-4bef-b7ca-1812f6d94753</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
