<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Topic Sport</name>
   <tag></tag>
   <elementGuidId>31dd9010-cd3d-4fce-9982-90a53b84a9fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div/div/div[1]/main/div/section/div/div/div/div/div[2]/div/div/section/div/div[1]/table/tbody/tr[2]/td[2]/a/span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div/section/div/div/div/div/div[2]/div/div/section/div/div/table/tbody/tr[2]/td[2]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>33fa84e2-d9cc-4447-abe0-f0af10b47598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
  Sport
</value>
      <webElementGuid>c88c6c3b-cc8b-40c0-9b1e-c7355b9f0a6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div/div[1]/main/div/section/div/div/div/div/div[2]/div/div/section/div/div[1]/table/tbody/tr[2]/td[2]/a/span</value>
      <webElementGuid>e50f8a84-8549-4014-a1be-b583c1dac760</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/section/div/div/div/div/div[2]/div/div/section/div/div/table/tbody/tr[2]/td[2]/a/span</value>
      <webElementGuid>def5b6cb-e432-4a6d-92f9-61fcedb15f41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Follow'])[1]/following::span[1]</value>
      <webElementGuid>fee40f1d-393b-41ec-9d61-8247fa89c466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Food'])[1]/following::span[2]</value>
      <webElementGuid>14d44077-5930-410b-9cb6-10c4a9359658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Follow'])[2]/preceding::span[1]</value>
      <webElementGuid>f0aa6b7e-7a9e-4213-995a-fef7e1144bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hewan'])[1]/preceding::span[2]</value>
      <webElementGuid>d17efc1e-b5d5-472f-b6fd-40ce53b697b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sport']/parent::*</value>
      <webElementGuid>406aa98b-f1e7-4a45-bcda-ada0a24078e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/a/span</value>
      <webElementGuid>4a0e011d-80a8-4f2d-b464-56d14612f7a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
  Sport
' or . = '
  Sport
')]</value>
      <webElementGuid>b7b78299-beaa-43c0-9173-8324d38c0f95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
