<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Validasi_Tentang Topik Ini</name>
   <tag></tag>
   <elementGuidId>86e7b5a7-2bef-453c-a94b-766cfd91e5f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h4.font-weight-medium</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div/div/div[3]/div[2]/div/div[2]/div/div/div/div/div/div/div/h4</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div/div/div/main/div/div/div[3]/div[2]/div/div[2]/div/div[1]/div/div/div/div[1]/div[1]/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>c0bd9046-c984-4581-ba3c-db0a19d63b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-weight-medium</value>
      <webElementGuid>3334c92d-6607-4df5-b953-66df513fd14a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tentang Topik Ini</value>
      <webElementGuid>b79dd793-c43e-42bc-a822-006cba4393a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div/div/main/div/div/div[3]/div[2]/div/div[2]/div/div[1]/div/div/div/div[1]/div[1]/h4</value>
      <webElementGuid>59901eda-eaa8-4814-820b-a6d4bdb031a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[3]/div[2]/div/div[2]/div/div/div/div/div/div/div/h4</value>
      <webElementGuid>148c3068-8dc5-48f2-8af0-af2fd9f36838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='@Elfnov1234'])[1]/following::h4[1]</value>
      <webElementGuid>6b22b98a-e530-4641-9bf7-06f3a9ea648a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sport'])[2]/preceding::h4[1]</value>
      <webElementGuid>96262e43-ce7b-4ae0-8c3e-ad90315fe5de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tentang olahraga'])[1]/preceding::h4[1]</value>
      <webElementGuid>10c6c5d4-2a4e-401a-8d79-49b67ab3b479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tentang Topik Ini']/parent::*</value>
      <webElementGuid>8f26fc81-83fe-4b45-9a5c-c8a124c188a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>fb2f86fc-cbd2-4537-877a-9e7002be4ea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Tentang Topik Ini' or . = 'Tentang Topik Ini')]</value>
      <webElementGuid>504174fe-e681-4557-aa0f-ad7e33a52449</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
