<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_User Banner</name>
   <tag></tag>
   <elementGuidId>45ec1728-247f-4ed7-99c8-0b815cda4564</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.rounded-lg.px-2.v-card.v-card--link.v-sheet.v-sheet--outlined.theme--light</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/header/div/div[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>15f84e72-1413-4b78-a842-6cf5484326b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0ff298ea-cea8-4b40-b701-2c519881929f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-lg px-2 v-card v-card--link v-sheet v-sheet--outlined theme--light</value>
      <webElementGuid>4b431b14-3115-44f2-9761-1751d2a0b00a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c04a3ff3-711a-4753-bbdd-a58d487b2465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c043f192-7308-4c85-9527-eb69c7bc5cd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>956e2949-2236-479d-a957-ebfa37ec5e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
                          babyyaga30
                         
                          User
                         </value>
      <webElementGuid>3cbd17d5-e1ad-414e-bc76-01bea3e1c307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div/div[1]/header/div/div[5]</value>
      <webElementGuid>7455d098-b06c-44b2-a7b9-624812b6b082</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/header/div/div[5]</value>
      <webElementGuid>cd916ae7-c1ec-48a0-9808-a5e4667192c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stations'])[1]/following::div[11]</value>
      <webElementGuid>a719031b-9ef4-47ea-a557-6eaa7bd49382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ranking'])[1]/following::div[13]</value>
      <webElementGuid>9c8ea9f7-3f72-4db3-9bd2-b53b20193d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]</value>
      <webElementGuid>f8a1a686-106c-49d4-81e4-80f1f06b2e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' 
                          babyyaga30
                         
                          User
                         ' or . = ' 
                          babyyaga30
                         
                          User
                         ')]</value>
      <webElementGuid>0874462a-af7e-4995-a002-71c20dceef3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
