<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search Bar banned page</name>
   <tag></tag>
   <elementGuidId>66455f91-f1dc-4aed-9957-106bbc070c34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-958</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-958']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div/div/div/main/div/section/section/div/div/div[3]/div/div/div/div[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ab47198-0be2-48ff-ab08-b2fbd859381c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-958</value>
      <webElementGuid>5e006e9f-bf59-47c3-93cd-a3968e58e006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>17b193d1-1fee-4b8d-b3d5-dc70dece0d2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div/div/main/div/section/section/div/div/div[3]/div/div/div/div[1]/input</value>
      <webElementGuid>3a78e0a7-eeff-4edc-badf-365b7aecc186</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-958']</value>
      <webElementGuid>5b2bba68-6bce-4591-902f-9765d9827b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div[3]/div/div/div/div/input</value>
      <webElementGuid>00753479-41b1-4bbb-a49e-dad7f7c0c5cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>eed85180-a367-405d-83f2-45e4250b1e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-958' and @type = 'text']</value>
      <webElementGuid>c59d7dc7-991a-4461-8ed5-d2bc8b7be0f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
