<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Permintaan moderator berhasil diterima</name>
   <tag></tag>
   <elementGuidId>e8d6d03a-cd85-467d-94a5-f379aa14af9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.v-snack__content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[3]/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>920a9966-c8ff-4b91-967d-00141407cab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>aa6fe0e3-0ac8-468c-ad70-0ad704c02180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>f9bcae2b-d04f-4d65-b497-0155eb6a4f37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-snack__content</value>
      <webElementGuid>5835b297-c1d8-4330-8f95-dd6085ff9e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    Permintaan moderator berhasil diterima
    </value>
      <webElementGuid>d8798725-bdfb-4fce-8f69-1d270798c151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div/div[3]/div/div[1]/div/div[1]</value>
      <webElementGuid>aae455a1-26a3-4aae-b3da-de42687d5d1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/div/div/div/div</value>
      <webElementGuid>97a60993-dd12-48f6-89f6-06ea2a72f8c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NaNm'])[9]/following::div[19]</value>
      <webElementGuid>6622950e-b015-4359-8b8b-0794fc4b2247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::div[1]</value>
      <webElementGuid>88eda101-b3e8-4677-88ab-b3e06dc672ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terjadi kesalahan saat menerima permintaan moderator'])[1]/preceding::div[2]</value>
      <webElementGuid>9f7e7ed7-2939-44be-9f4d-151f485dc19e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Permintaan moderator berhasil diterima']/parent::*</value>
      <webElementGuid>421134e5-2dd3-4576-88cb-929786864063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div</value>
      <webElementGuid>5c2d6770-7789-45ab-803b-281aa32fcd07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
    Permintaan moderator berhasil diterima
    ' or . = '
    Permintaan moderator berhasil diterima
    ')]</value>
      <webElementGuid>b7d8c2fb-d574-49e5-afbe-a5aec0ac72f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
