<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ID Profile</name>
   <tag></tag>
   <elementGuidId>b04fc3c6-de4e-4fcc-a7d6-297da9d711b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.rounded-lg.px-2.v-card.v-card--link.v-sheet.v-sheet--outlined.theme--light</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/header/div/div[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f39abb3a-9744-4bf2-9b0e-5e2f62356ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2c42eb0b-b866-4097-b66c-25ff8afd9e44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-lg px-2 v-card v-card--link v-sheet v-sheet--outlined theme--light</value>
      <webElementGuid>b33da0aa-a805-4d04-9a8b-c478c0c816ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>de8b935c-0cce-490c-9b5a-0033f2cf8d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7b1f89d4-ae3e-42dc-9fef-da7b7ef15d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fc3409d9-ba63-4998-865e-4a597ed2e2d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
                          Elf123456
                         
                          User
                         </value>
      <webElementGuid>7fd4a603-52d9-44d5-97c3-1d0e4ee1232c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/header[@class=&quot;v-sheet theme--light v-toolbar v-app-bar v-app-bar--fixed&quot;]/div[@class=&quot;v-toolbar__content&quot;]/div[@class=&quot;rounded-lg px-2 v-card v-card--link v-sheet v-sheet--outlined theme--light&quot;]</value>
      <webElementGuid>1f69c34a-7a91-4975-bce1-0287e387f0e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/header/div/div[5]</value>
      <webElementGuid>0b83d6da-dbd8-44c3-ba59-a76b8d5ebc33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stations'])[1]/following::div[11]</value>
      <webElementGuid>da3ebcb7-8e0b-48d6-86ea-811c4304e921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ranking'])[1]/following::div[13]</value>
      <webElementGuid>c5331eb6-5a2c-436e-8a86-b89cfb5d4508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]</value>
      <webElementGuid>90f99db1-81f6-4ba8-8365-2897c985d03d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' 
                          Elf123456
                         
                          User
                         ' or . = ' 
                          Elf123456
                         
                          User
                         ')]</value>
      <webElementGuid>59852678-cae7-4c1d-b7e8-0277f16da0fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
