<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Email Field</name>
   <tag></tag>
   <elementGuidId>b7952584-16c6-47b0-bb7c-5db3fb67ac0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-1250</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-1250']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f760b753-aa09-4665-9af9-ac9be45425f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-1250</value>
      <webElementGuid>a07dff55-921e-4c6f-a4b4-2870fba34fac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6717989c-2ff0-4934-8c7e-a1f7b52d1728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-1250&quot;)</value>
      <webElementGuid>d37c9995-e03b-4f28-b75a-f718f0106307</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-1250']</value>
      <webElementGuid>f7f1002f-42a4-43ea-be24-fa6ab0ae5d32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>62a6ca9c-419f-421b-93a0-c39acf304889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>b56175f7-e1a3-4ab5-a145-fb68b9f30fab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-1250' and @type = 'text']</value>
      <webElementGuid>047bfe20-1390-4164-a0ac-888ed9172015</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
